### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by LeoBdt** [A354-PH/AFK#1]
Hello, could you add an automatic afk system?

For example : Player is idling for X second, it says "you're now afk" and After X seconds or being afk it kicks the player.

**Comment by A354-PH** [comment]
Thanks for the suggestion! I will add on the next update!

P.S:  Did the plugin worked? I havent tested it lmao

**Comment by LeoBdt** [comment]
i haven't tested it too loooool.

**Comment by A354-PH** [comment]
Lmao

**Comment by LeoBdt** [comment]
????
